name: Terraform Create - EC2 and S3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
            aws-region: ap-south-1
  
      - name: Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Initializing Terraform
        run: |
          cd TfModules/
          terraform init
          terraform plan
          terraform apply -auto-approve
